### ISSUE TITLE
TracebackError in duck2spark.py

### ISSUE THREAD

**Issue by Moritz448** [mame82/duck2spark#15]
Hi mame82, i found an Error under Windows: If i run the duck2spark.py, i got this error:
`Traceback (most recent call last):
  File "duck2spark.py", line 155, in <module>
    main(sys.argv[1:])
  File "duck2spark.py", line 140, in main
    result = generate_source(payload, init_delay=init_delay, loop_count=loop_count, loop_delay=loop_delay, blink=blink)
  File "duck2spark.py", line 65, in generate_source
    declare += str(hex(ord(payload[c]))) + ", "
TypeError: ord() expected string of length 1, but int found`

I've typed in this:
 ` python duck2spark.py -i ../../example.bin -l 4 -f 2500 -r 3000 -o example.ino`
Can you say me how to fix it?7

Thx,
Moritz

EDIT: Looks like this: [https://github.com/mame82/duck2spark/pull/10](https://github.com/mame82/duck2spark/pull/10)

**Comment by Moritz448** [comment]
I fixed it easy: Removed the ord() in line 65 and 66
