### ISSUE TITLE
TypeError: ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by antoninhrlt** [mame82/duck2spark#18]
Hey ! I've downloaded duck2spark from github, and when I want to run it, an error happen
My command: 
```bash
python3 duck2spark/duck2spark.py -i ducky.bin -o Payload.bin
```
Error:
```
Traceback (most recent call last):
  File "duck2spark/duck2spark.py", line 155, in <module>
    main(sys.argv[1:])
  File "duck2spark/duck2spark.py", line 140, in main
    result = generate_source(payload, init_delay=init_delay, loop_count=loop_count, loop_delay=loop_delay, blink=blink)
  File "duck2spark/duck2spark.py", line 65, in generate_source
    declare += str(hex(ord(payload[c]))) + ", "
TypeError: ord() expected string of length 1, but int found
```

**Comment by antoninhrlt** [comment]
If you have the same problem, look at [this](https://github.com/mame82/duck2spark/pull/10/files)
